# Generated by Django 4.2.3 on 2023-08-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicine_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='company', max_length=100),
        ),
    ]
