# Generated by Django 4.2.3 on 2023-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_medicine_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
