# Generated by Django 4.2.3 on 2023-08-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_medicine_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
